In [51]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [54]:
dataset = pd.read_csv(r"Dataset\Churn\Churn.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [55]:
print(dataset.shape)

(10000, 14)


In [56]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [57]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [58]:
print(y)

[1 0 1 ... 1 1 0]


In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[: ,2])

In [60]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# Encoding

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Building the ANN

### Initializing the ANN

In [64]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [65]:
# ann.add(tf.keras.Input(shape = (11,)))

In [66]:
ann.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))

### Adding the second hidden layer

In [67]:
ann.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))

### Adding the third hidden layer

In [68]:
ann.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))

### Adding the output layer

In [69]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Part 3 - Training the ANN

### Compiling the ANN

In [70]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [71]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 150)

Epoch 1/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4600 - accuracy: 0.7996
Epoch 2/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4071 - accuracy: 0.8235
Epoch 3/150
250/250 [==============================] - 1s 2ms/step - loss: 0.3744 - accuracy: 0.8462
Epoch 4/150
250/250 [==============================] - 1s 2ms/step - loss: 0.3522 - accuracy: 0.8562
Epoch 5/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8596
Epoch 6/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8614
Epoch 7/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8615
Epoch 8/150
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8644
Epoch 9/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3252 - accuracy: 0.8650
Epoch 10/150
250/250 [==============================] - 0s 2ms/step - loss: 0.3238 - accura

# Part 4 - Making the prediction 

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [72]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 61ms/step
[[False]]


### Predicting the Test set results

In [73]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 892us/step
[[1 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1438  157]
 [ 186  219]]


0.8285

In [75]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 32)                416       
                                                                 
 dense_9 (Dense)             (None, 32)                1056      
                                                                 
 dense_10 (Dense)            (None, 32)                1056      
                                                                 
 dense_11 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2,561
Trainable params: 2,561
Non-trainable params: 0
_________________________________________________________________
