In [1]:
import numpy as np

In [3]:
arr = [1,2,3,4,5,6]
ndarr = np.array(arr)
print(ndarr)

[1 2 3 4 5 6]


In [9]:
arr2 = [[1,2,3],[4,5,6]]
ndarr2 = np.array(arr2)
print(ndarr2)
print(ndarr2.shape)
print(ndarr2.size)
print(ndarr2.ndim)
print(type(ndarr2))
print(ndarr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
<class 'numpy.ndarray'>
int32


In [11]:
import pandas as pd
a = [1,2,3,4,5]
a = np.array(a)
df = pd.DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [37]:
import pandas as pd
a = [['Sujal', 18], ['Neelesh',19],['Harsh',20]]
df = pd.DataFrame(a, columns=['Name', 'Age'])
print(df)

      Name  Age
0    Sujal   18
1  Neelesh   19
2    Harsh   20


In [16]:
import pandas as pd
a = [['Sujal', 18], ['Neelesh',19],['Harsh',20]]
x_index = ['Name','Age']
y_index = ['First','Second','Third']
a = np.array(a)
df = pd.DataFrame(data = a, index = y_index, columns = x_index)
print(df)

           Name Age
First     Sujal  18
Second  Neelesh  19
Third     Harsh  20


In [22]:
import pandas as pd
a = {'Name':['Sujal','Neelesh','Harsh'],'Age':[18,19,20]}
df = pd.DataFrame(data = a)
print(df)

      Name  Age
0    Sujal   18
1  Neelesh   19
2    Harsh   20


In [26]:
df = pd.read_csv('Salary_Data.csv')
print(df)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0
