# <center>**TF / IDF**</center>

**TF** - log(D/Di) <br/>
**D** -> No. of documents <br/>
**Di** -> Word contains in how many documents <br/> <br/>


**IDF** - TF * Freq

**Query array must be multiplied to find documents**

## **Python Lib**
### **Word Embedding Technique** <br/>
**TF / IDF Vectorizer** <br/>
**Count Vectorizer** <br/>
**Glove** <br/>
**FastTex** <br/>
**BERT** <br/>
**GPT** <br/>
**One-Hot Encoder** <br/>
**Word2Vec** <br/>

In [109]:
import nltk
from nltk.tokenize import word_tokenize
import numpy as np

In [110]:
str1 = "In the 21st century, digital technology has transformed the way we approach education, making online learning platforms more popular than ever before."
str2 = "The stock market experienced a significant downturn last week, leading to concerns about the overall health of the global economy."
str3 = "The Olympic Games are a showcase of human athleticism and international unity, bringing together athletes from all corners of the world to compete on a grand stage."

In [111]:
str1_list = word_tokenize(str1)
str2_list = word_tokenize(str2)
str3_list = word_tokenize(str3)

In [112]:
print(str1_list)
print(str2_list)
print(str3_list)

['In', 'the', '21st', 'century', ',', 'digital', 'technology', 'has', 'transformed', 'the', 'way', 'we', 'approach', 'education', ',', 'making', 'online', 'learning', 'platforms', 'more', 'popular', 'than', 'ever', 'before', '.']
['The', 'stock', 'market', 'experienced', 'a', 'significant', 'downturn', 'last', 'week', ',', 'leading', 'to', 'concerns', 'about', 'the', 'overall', 'health', 'of', 'the', 'global', 'economy', '.']
['The', 'Olympic', 'Games', 'are', 'a', 'showcase', 'of', 'human', 'athleticism', 'and', 'international', 'unity', ',', 'bringing', 'together', 'athletes', 'from', 'all', 'corners', 'of', 'the', 'world', 'to', 'compete', 'on', 'a', 'grand', 'stage', '.']


In [113]:
li = []
li += str1_list
li += str2_list
li += str3_list
li

['In',
 'the',
 '21st',
 'century',
 ',',
 'digital',
 'technology',
 'has',
 'transformed',
 'the',
 'way',
 'we',
 'approach',
 'education',
 ',',
 'making',
 'online',
 'learning',
 'platforms',
 'more',
 'popular',
 'than',
 'ever',
 'before',
 '.',
 'The',
 'stock',
 'market',
 'experienced',
 'a',
 'significant',
 'downturn',
 'last',
 'week',
 ',',
 'leading',
 'to',
 'concerns',
 'about',
 'the',
 'overall',
 'health',
 'of',
 'the',
 'global',
 'economy',
 '.',
 'The',
 'Olympic',
 'Games',
 'are',
 'a',
 'showcase',
 'of',
 'human',
 'athleticism',
 'and',
 'international',
 'unity',
 ',',
 'bringing',
 'together',
 'athletes',
 'from',
 'all',
 'corners',
 'of',
 'the',
 'world',
 'to',
 'compete',
 'on',
 'a',
 'grand',
 'stage',
 '.']

In [114]:
len(li)

76

In [115]:
li = set(li)
print(li)

{'health', 'and', 'unity', 'bringing', 'has', 'concerns', 'we', '21st', 'ever', 'stock', 'experienced', 'about', 'athletes', 'way', '.', 'significant', 'all', 'athleticism', 'showcase', 'technology', 'learning', ',', 'of', 'human', 'overall', 'The', 'downturn', 'stage', 'last', 'a', 'international', 'week', 'education', 'online', 'corners', 'before', 'In', 'approach', 'market', 'economy', 'digital', 'Games', 'are', 'popular', 'from', 'Olympic', 'more', 'than', 'to', 'compete', 'grand', 'leading', 'making', 'together', 'global', 'transformed', 'on', 'century', 'platforms', 'the', 'world'}


In [116]:
len(li)

61

In [117]:
mat = []
i = 0
for tot_token in li:
    counter = 0
    mat.append([tot_token, 0, 0, 0])
    if tot_token in str1_list:
        for token in str1_list:
            if (token == tot_token):
                counter += 1
        mat[i][1] = counter
        counter = 0
    if tot_token in str2_list:
        for token in str2_list:
            if (token == tot_token):
                counter += 1
        mat[i][2] = counter
        counter = 0
    if tot_token in str3_list:
        for token in str3_list:
            if (token == tot_token):
                counter += 1
        mat[i][3] = counter
        counter = 0
    i += 1

print(mat)

[['health', 0, 1, 0], ['and', 0, 0, 1], ['unity', 0, 0, 1], ['bringing', 0, 0, 1], ['has', 1, 0, 0], ['concerns', 0, 1, 0], ['we', 1, 0, 0], ['21st', 1, 0, 0], ['ever', 1, 0, 0], ['stock', 0, 1, 0], ['experienced', 0, 1, 0], ['about', 0, 1, 0], ['athletes', 0, 0, 1], ['way', 1, 0, 0], ['.', 1, 1, 1], ['significant', 0, 1, 0], ['all', 0, 0, 1], ['athleticism', 0, 0, 1], ['showcase', 0, 0, 1], ['technology', 1, 0, 0], ['learning', 1, 0, 0], [',', 2, 1, 1], ['of', 0, 1, 2], ['human', 0, 0, 1], ['overall', 0, 1, 0], ['The', 0, 1, 1], ['downturn', 0, 1, 0], ['stage', 0, 0, 1], ['last', 0, 1, 0], ['a', 0, 1, 2], ['international', 0, 0, 1], ['week', 0, 1, 0], ['education', 1, 0, 0], ['online', 1, 0, 0], ['corners', 0, 0, 1], ['before', 1, 0, 0], ['In', 1, 0, 0], ['approach', 1, 0, 0], ['market', 0, 1, 0], ['economy', 0, 1, 0], ['digital', 1, 0, 0], ['Games', 0, 0, 1], ['are', 0, 0, 1], ['popular', 1, 0, 0], ['from', 0, 0, 1], ['Olympic', 0, 0, 1], ['more', 1, 0, 0], ['than', 1, 0, 0], ['to', 

In [118]:
tf = np.array(mat)
tf

array([['health', '0', '1', '0'],
       ['and', '0', '0', '1'],
       ['unity', '0', '0', '1'],
       ['bringing', '0', '0', '1'],
       ['has', '1', '0', '0'],
       ['concerns', '0', '1', '0'],
       ['we', '1', '0', '0'],
       ['21st', '1', '0', '0'],
       ['ever', '1', '0', '0'],
       ['stock', '0', '1', '0'],
       ['experienced', '0', '1', '0'],
       ['about', '0', '1', '0'],
       ['athletes', '0', '0', '1'],
       ['way', '1', '0', '0'],
       ['.', '1', '1', '1'],
       ['significant', '0', '1', '0'],
       ['all', '0', '0', '1'],
       ['athleticism', '0', '0', '1'],
       ['showcase', '0', '0', '1'],
       ['technology', '1', '0', '0'],
       ['learning', '1', '0', '0'],
       [',', '2', '1', '1'],
       ['of', '0', '1', '2'],
       ['human', '0', '0', '1'],
       ['overall', '0', '1', '0'],
       ['The', '0', '1', '1'],
       ['downturn', '0', '1', '0'],
       ['stage', '0', '0', '1'],
       ['last', '0', '1', '0'],
       ['a', '0', '1', '2'

In [119]:
tot_doc = 3
log_sheet = []
for item in tf:
    contain_doc = 0
    for i in range(1, 4):
        if int(item[i]) > 0:
            contain_doc += 1
    data = np.log10(tot_doc/contain_doc)
    log_sheet.append([data, data, data])
    
log_sheet =np.array(log_sheet)
print(log_sheet)


[[0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.         0.         0.        ]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.         0.         0.        ]
 [0.17609126 0.17609126 0.17609126]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.17609126 0.17609126 0.17609126]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47

In [120]:
# IDF
tf = np.delete(tf, 0, 1)
tf

array([['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['0', '1', '0'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['1', '1', '1'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['2', '1', '1'],
       ['0', '1', '2'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '1', '1'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '1', '2'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['0', '1', '0'],
       ['1', '0', '0'],
       ['0', '0'

In [121]:
print(len(log_sheet))
print(len(tf))

61
61


In [122]:
idf = np.multiply(tf, log_sheet)
print(idf)

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U13'), dtype('float64')) -> None