# <center>**TF / IDF**</center>

**IDF** - log(D/Di) <br/>
**D** -> No. of documents <br/>
**Di** -> Word contains in how many documents <br/> <br/>


**TF** - Freq of that particular word / Total No. of words

**Query array must be multiplied to find documents**

## **Python Lib**
### **Word Embedding Technique** <br/>
**TF / IDF Vectorizer** <br/>
**Count Vectorizer** <br/>
**Glove** <br/>
**FastTex** <br/>
**BERT** <br/>
**GPT** <br/>
**One-Hot Encoder** <br/>
**Word2Vec** <br/>

In [1]:
import nltk
from nltk.tokenize import word_tokenize
import numpy as np

In [2]:
str1 = "In the 21st century, digital technology has transformed the way we approach education, making online learning platforms more popular than ever before."
str2 = "The stock market experienced a significant downturn last week, leading to concerns about the overall health of the global economy."
str3 = "The Olympic Games are a showcase of human athleticism and international unity, bringing together athletes from all corners of the world to compete on a grand stage."

In [3]:
str1_list = word_tokenize(str1)
str2_list = word_tokenize(str2)
str3_list = word_tokenize(str3)

In [4]:
print(str1_list)
print(str2_list)
print(str3_list)

['In', 'the', '21st', 'century', ',', 'digital', 'technology', 'has', 'transformed', 'the', 'way', 'we', 'approach', 'education', ',', 'making', 'online', 'learning', 'platforms', 'more', 'popular', 'than', 'ever', 'before', '.']
['The', 'stock', 'market', 'experienced', 'a', 'significant', 'downturn', 'last', 'week', ',', 'leading', 'to', 'concerns', 'about', 'the', 'overall', 'health', 'of', 'the', 'global', 'economy', '.']
['The', 'Olympic', 'Games', 'are', 'a', 'showcase', 'of', 'human', 'athleticism', 'and', 'international', 'unity', ',', 'bringing', 'together', 'athletes', 'from', 'all', 'corners', 'of', 'the', 'world', 'to', 'compete', 'on', 'a', 'grand', 'stage', '.']


In [5]:
li = []
li += str1_list
li += str2_list
li += str3_list
li

['In',
 'the',
 '21st',
 'century',
 ',',
 'digital',
 'technology',
 'has',
 'transformed',
 'the',
 'way',
 'we',
 'approach',
 'education',
 ',',
 'making',
 'online',
 'learning',
 'platforms',
 'more',
 'popular',
 'than',
 'ever',
 'before',
 '.',
 'The',
 'stock',
 'market',
 'experienced',
 'a',
 'significant',
 'downturn',
 'last',
 'week',
 ',',
 'leading',
 'to',
 'concerns',
 'about',
 'the',
 'overall',
 'health',
 'of',
 'the',
 'global',
 'economy',
 '.',
 'The',
 'Olympic',
 'Games',
 'are',
 'a',
 'showcase',
 'of',
 'human',
 'athleticism',
 'and',
 'international',
 'unity',
 ',',
 'bringing',
 'together',
 'athletes',
 'from',
 'all',
 'corners',
 'of',
 'the',
 'world',
 'to',
 'compete',
 'on',
 'a',
 'grand',
 'stage',
 '.']

In [6]:
len(li)

76

In [7]:
li = set(li)
print(li)

{'we', 'approach', 'leading', 'grand', 'the', 'global', 'stage', 'popular', 'all', 'Olympic', 'and', 'compete', 'transformed', 'of', 'on', 'making', 'ever', 'The', 'market', 'international', 'significant', 'concerns', 'to', 'platforms', 'together', 'century', 'economy', 'more', '21st', 'than', 'athleticism', 'showcase', 'week', 'corners', 'experienced', 'last', 'world', 'from', 'a', 'before', 'downturn', ',', 'digital', 'learning', 'stock', 'about', 'Games', 'athletes', 'human', 'are', 'technology', 'health', 'has', 'education', 'way', 'In', 'online', '.', 'bringing', 'overall', 'unity'}


In [8]:
len(li)

61

In [9]:
mat = []
i = 0
for tot_token in li:
    counter = 0
    mat.append([tot_token, 0, 0, 0])
    if tot_token in str1_list:
        for token in str1_list:
            if (token == tot_token):
                counter += 1
        mat[i][1] = counter
        counter = 0
    if tot_token in str2_list:
        for token in str2_list:
            if (token == tot_token):
                counter += 1
        mat[i][2] = counter
        counter = 0
    if tot_token in str3_list:
        for token in str3_list:
            if (token == tot_token):
                counter += 1
        mat[i][3] = counter
        counter = 0
    i += 1

print(mat)

[['we', 1, 0, 0], ['approach', 1, 0, 0], ['leading', 0, 1, 0], ['grand', 0, 0, 1], ['the', 2, 2, 1], ['global', 0, 1, 0], ['stage', 0, 0, 1], ['popular', 1, 0, 0], ['all', 0, 0, 1], ['Olympic', 0, 0, 1], ['and', 0, 0, 1], ['compete', 0, 0, 1], ['transformed', 1, 0, 0], ['of', 0, 1, 2], ['on', 0, 0, 1], ['making', 1, 0, 0], ['ever', 1, 0, 0], ['The', 0, 1, 1], ['market', 0, 1, 0], ['international', 0, 0, 1], ['significant', 0, 1, 0], ['concerns', 0, 1, 0], ['to', 0, 1, 1], ['platforms', 1, 0, 0], ['together', 0, 0, 1], ['century', 1, 0, 0], ['economy', 0, 1, 0], ['more', 1, 0, 0], ['21st', 1, 0, 0], ['than', 1, 0, 0], ['athleticism', 0, 0, 1], ['showcase', 0, 0, 1], ['week', 0, 1, 0], ['corners', 0, 0, 1], ['experienced', 0, 1, 0], ['last', 0, 1, 0], ['world', 0, 0, 1], ['from', 0, 0, 1], ['a', 0, 1, 2], ['before', 1, 0, 0], ['downturn', 0, 1, 0], [',', 2, 1, 1], ['digital', 1, 0, 0], ['learning', 1, 0, 0], ['stock', 0, 1, 0], ['about', 0, 1, 0], ['Games', 0, 0, 1], ['athletes', 0, 0, 1

In [10]:
tf = np.array(mat)
tf

array([['we', '1', '0', '0'],
       ['approach', '1', '0', '0'],
       ['leading', '0', '1', '0'],
       ['grand', '0', '0', '1'],
       ['the', '2', '2', '1'],
       ['global', '0', '1', '0'],
       ['stage', '0', '0', '1'],
       ['popular', '1', '0', '0'],
       ['all', '0', '0', '1'],
       ['Olympic', '0', '0', '1'],
       ['and', '0', '0', '1'],
       ['compete', '0', '0', '1'],
       ['transformed', '1', '0', '0'],
       ['of', '0', '1', '2'],
       ['on', '0', '0', '1'],
       ['making', '1', '0', '0'],
       ['ever', '1', '0', '0'],
       ['The', '0', '1', '1'],
       ['market', '0', '1', '0'],
       ['international', '0', '0', '1'],
       ['significant', '0', '1', '0'],
       ['concerns', '0', '1', '0'],
       ['to', '0', '1', '1'],
       ['platforms', '1', '0', '0'],
       ['together', '0', '0', '1'],
       ['century', '1', '0', '0'],
       ['economy', '0', '1', '0'],
       ['more', '1', '0', '0'],
       ['21st', '1', '0', '0'],
       ['than', '1

In [11]:
tot_doc = 3
log_sheet = []
for item in tf:
    contain_doc = 0
    for i in range(1, 4):
        if int(item[i]) > 0:
            contain_doc += 1
    data = np.log10(tot_doc/contain_doc)
    log_sheet.append([data, data, data])
    
log_sheet =np.array(log_sheet)
print(log_sheet)


[[0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.         0.         0.        ]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.17609126 0.17609126 0.17609126]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.17609126 0.17609126 0.17609126]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.17609126 0.17609126 0.17609126]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47712125]
 [0.47712125 0.47712125 0.47

In [12]:
# IDF
tf = np.delete(tf, 0, 1)
tf

array([['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['2', '2', '1'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['0', '1', '2'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '1', '1'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '1', '0'],
       ['0', '1', '1'],
       ['1', '0', '0'],
       ['0', '0', '1'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['1', '0', '0'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '1', '0'],
       ['0', '0', '1'],
       ['0', '0', '1'],
       ['0', '1', '2'],
       ['1', '0', '0'],
       ['0', '1', '0'],
       ['2', '1'

In [13]:
docdiv1 = len(str1)
docdiv2 = len(str2)
docdiv3 = len(str3)

for item in tf:
    item[0] = int(item[0])/docdiv1
    item[1] = int(item[1])/docdiv2
    item[2] = int(item[2])/docdiv3

In [14]:
print(len(log_sheet))
print(len(tf))
print(tf)

61
61
[['0.00666666666' '0.0' '0.0']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.00769230769' '0.0']
 ['0.0' '0.0' '0.00609756097']
 ['0.01333333333' '0.01538461538' '0.00609756097']
 ['0.0' '0.00769230769' '0.0']
 ['0.0' '0.0' '0.00609756097']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.0' '0.00609756097']
 ['0.0' '0.0' '0.00609756097']
 ['0.0' '0.0' '0.00609756097']
 ['0.0' '0.0' '0.00609756097']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.00769230769' '0.01219512195']
 ['0.0' '0.0' '0.00609756097']
 ['0.00666666666' '0.0' '0.0']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.00769230769' '0.00609756097']
 ['0.0' '0.00769230769' '0.0']
 ['0.0' '0.0' '0.00609756097']
 ['0.0' '0.00769230769' '0.0']
 ['0.0' '0.00769230769' '0.0']
 ['0.0' '0.00769230769' '0.00609756097']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.0' '0.00609756097']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.00769230769' '0.0']
 ['0.00666666666' '0.0' '0.0']
 ['0.00666666666' '0.0' '0.0']
 ['0.00666666666' '0.0' '0.0']
 ['0.0' '0.0' 

In [15]:
search = tf.astype('float64') * log_sheet

In [18]:
search

array([[0.00318081, 0.        , 0.        ],
       [0.00318081, 0.        , 0.        ],
       [0.        , 0.00367016, 0.        ],
       [0.        , 0.        , 0.00290928],
       [0.        , 0.        , 0.        ],
       [0.        , 0.00367016, 0.        ],
       [0.        , 0.        , 0.00290928],
       [0.00318081, 0.        , 0.        ],
       [0.        , 0.        , 0.00290928],
       [0.        , 0.        , 0.00290928],
       [0.        , 0.        , 0.00290928],
       [0.        , 0.        , 0.00290928],
       [0.00318081, 0.        , 0.        ],
       [0.        , 0.00135455, 0.00214745],
       [0.        , 0.        , 0.00290928],
       [0.00318081, 0.        , 0.        ],
       [0.00318081, 0.        , 0.        ],
       [0.        , 0.00135455, 0.00107373],
       [0.        , 0.00367016, 0.        ],
       [0.        , 0.        , 0.00290928],
       [0.        , 0.00367016, 0.        ],
       [0.        , 0.00367016, 0.        ],
       [0.